// IMPLEMENTS: docs/tech/09_data_model/schema_player_economy_state.md §4.2 (iap_transactions, day-0
//             migration 0003) + design §3-C4 ("l'anti-rejeu est la contrainte de base — l'insertion
//             attrape la violation de iap_transactions_platform_receipt_uq et la traduit en rejeu
//             idempotent, jamais un SELECT préalable — TOCTOU sur un chemin d'argent").
// -- W1.3-C4 -- 2026-08-13 --
// -- FIX (review ⊥ B1, 2026-08-13) -- the `lifetime_iap_value_cents`/`last_iap_at` `UPDATE` below
//    had NO cardinality check (twin of `MarksWalletRepository.creditUnconditional`'s bug) — a
//    missing `economy_states` row made it match 0 rows silently, the caller committed the receipt
//    anyway, and the unique index (`0003:40`) then made that receipt PERMANENTLY unusable (every
//    replay takes the `DUPLICATE` branch and never re-credits). Fixed: `.returning()` + throw
//    `MissingEconomyStateRowError` (same sentinel `MarksWalletRepository` throws) on 0 rows.
//
// `IapTransactionRepository` — the FIRST writer of `iap_transactions` anywhere in this codebase
// (design §1.2 M6 — measured zero readers, zero writers before this chunk). `tx: Tx` REQUIRED
// (same discipline as every other write repository this lot adds) — inserts the transaction row
// AND updates `economy_states.{lifetime_iap_value_cents, last_iap_at}` in the SAME transaction
// (design §3-C4: "closes M4/M5 here").
//
// txn_id: generated by the APPLICATION (`0003:22` — the column has no `DEFAULT`; an INSERT that
// omits it fails at RUNTIME, invisible to `tsc` — design §1.1). Always passed explicitly here.

import { Injectable } from '@nestjs/common';
import { eq, sql } from 'drizzle-orm';

import type { DrizzleClient } from '../../db';
import { economyState, iapTransaction, type IapPlatformEnumTs } from '../../db/schema/player_economy_state';
import { MissingEconomyStateRowError } from './marks-wallet.repository';

/** A Drizzle transaction handle (mirrors money-holding.repository.ts:46's own local Tx alias). */
type Tx = Parameters<Parameters<DrizzleClient['transaction']>[0]>[0];

export interface RecordIapTransactionEntry {
  txnId: string;
  playerId: string;
  sku: string;
  amountCents: bigint;
  currencyCode: string;
  platform: IapPlatformEnumTs;
  platformReceipt: string;
  purchasedAt: Date;
}

export type RecordIapTransactionResult = 'INSERTED' | 'DUPLICATE';

/** Same 2-line `isUniqueViolation` idiom this codebase's "each repository keeps its own copy"
 *  convention uses (precedent: standing-order.service.ts:66-69) — a boolean-only check is enough
 *  here since only ONE unique index (`iap_transactions_platform_receipt_uq`) can fire on this
 *  insert (`txn_id` is a fresh app-generated uuid, never a collision in practice). */
function isUniqueViolation(e: unknown): boolean {
  const err = e as { code?: string; cause?: { code?: string } } | null;
  return err?.code === '23505' || err?.cause?.code === '23505';
}

@Injectable()
export class IapTransactionRepository {
  /**
   * Insert the transaction row. On a `platform_receipt_uq` violation (the SAME receipt already
   * recorded), returns 'DUPLICATE' instead of throwing — the anti-replay IS this constraint, never
   * a `SELECT` first (no TOCTOU window on a money path). On a fresh insert, also updates
   * `lifetime_iap_value_cents`/`last_iap_at` (M4/M5, design §1.2) in the SAME transaction.
   */
  async record(tx: Tx, entry: RecordIapTransactionEntry): Promise<RecordIapTransactionResult> {
    try {
      await tx.insert(iapTransaction).values({
        txn_id: entry.txnId,
        player_id: entry.playerId,
        sku: entry.sku,
        amount_cents: entry.amountCents,
        currency_code: entry.currencyCode,
        platform: entry.platform,
        platform_receipt: entry.platformReceipt,
        purchased_at: entry.purchasedAt,
      });
    } catch (err) {
      if (isUniqueViolation(err)) return 'DUPLICATE';
      throw err;
    }
    const rows = await tx
      .update(economyState)
      .set({
        lifetime_iap_value_cents: sql`${economyState.lifetime_iap_value_cents} + ${entry.amountCents}`,
        last_iap_at: entry.purchasedAt,
      })
      .where(eq(economyState.player_id, entry.playerId))
      .returning({ player_id: economyState.player_id });
    if (rows.length === 0) {
      // Rolls the WHOLE tx back — including the iap_transactions insert above — so the receipt
      // is NOT consumed (review ⊥ B1: the unique index would otherwise burn it forever).
      throw new MissingEconomyStateRowError(entry.playerId);
    }
    return 'INSERTED';
  }
}
