// IMPLEMENTS: docs/tech/09_data_model/drizzle_setup_and_migrations.md§2.3 -- session:2026-06-02 --
//
// Aggregated re-export barrel for drizzle() — one `export * from './<entity>'`
// per schema file (§2.3). The 16 schema_* entities of chapter 09 are re-exported
// here (Phase 0 Task 4), in FK-dependency order (reading_order_designers.md §2 :
// player → progression/economy → lieutenant → city_state → pipeline → queues →
// progression_structural → sparse_citizens → sessions_audit → anti_cheat →
// telemetry_event). drizzle(pool, { schema }) consumes the union (§2.2).
export * from './player';                       // Task 3 — root (FK convention player_id)
export * from './player_progression_state';     // Task 4 — 1-1 Player (+ mastery_score)
export * from './player_economy_state';         // Task 5 — 1-1 Player (+ iap_transactions, enum iap_platform)
export * from './lieutenant';                   // Task 6 — 7 tables + 9 enums (7 canon + granted_role + lieutenant_mode, Phase-6 vector #6 slice-1 migration 0026)
export * from './autonomy_ceiling';             // P19/T1 — autonomy_ceiling_state (1-1 CHILD of lieutenant, delegation budget + cycle; migration 0031) — FK-ordered right after its lieutenant parent
export * from './signal_drift';                  // P22/T1 — signal_drift_state (1-1 CHILD of lieutenant, cue-reliability registry + drift phase; migration 0032) — FK-ordered right after its lieutenant parent
export * from './standing_order_state';          // P25/T1 — standing_order_state (1-1 CHILD of lieutenant, lapse-pattern ledger + decision cooldowns; migration 0034) — FK-ordered right after its lieutenant parent
export * from './city_state';                   // Task 7 — 7 tables (districtCohesion/precinctMemory/patrolObservationQueue/inspectionQueue/building/dealLek/federalInvestigator, the last added 04e-A1 C7 mig 0108) — rival_state lives in conflict_rival.ts, not here
export * from './pipeline_and_laundering';      // Task 8 — laundering nodes/edges/safehouses/tail_risk
export * from './queues_exceptions_cuestack';   // Task 9 — exception_queue/cue_stacks/autonomy_reports
export * from './progression_structural';       // Task 10 — constraint_log/possibility_horizon_cards/recurrence_logs/structural_decisions_audit
export * from './sparse_citizens';              // Task 11 — rich_citizens
export * from './sessions_and_audit';           // Task 12 — gameplay_sessions + admin_audit_log (partitioned) + enum audit_action_type
export * from './anti_cheat';                   // A2 — cheat_flag/enforcement_action/appeal_case + 7 pgEnums
export * from './telemetry_event';              // A2 — telemetry_event (partitioned) + enums event_domain/event_privacy_class
export * from './account';                       // Task 6 (ch17) — account/staff_account/account_credential/auth_session + 6 pgEnums (owned by 17, NOT 09)
export * from './world_geography';              // P1/T0 — GLOBAL static map: districts/blocks/threnny_edges + 3 pgEnums (no player_id)
export * from './city_sim_clock';               // P1/T0 — per-save in-game clock (PK player_id seul)
export * from './operational_chain';            // P2/T0 — operational M1: building_operational_state/precursor_*/cook_session/product_storage/dealer/courier/route/courier_shift + 14 pgEnums ; P2b/T0 — +building_raid + 2 pgEnums (structural_state/repair raid surface §7)
export * from './tunable_overrides';            // P23/T1 — tunable_overrides (standalone infra KV store; key→value text override registry + NOTIFY trigger; migration 0033)
export * from './false_report_ledger';          // TD-012/lot-5 — false_report_ledger + false_report_ledger_summary (FalseReportLedger + flood backlash; migration 0036)
export * from './market_lane_pricing_state';    // D1b C2 — lane_pricing_state: global market lane state per (district_id × substance_type); migration 0038
export * from './market_buyer_roster_entry';   // D1b C3 — buyer_roster_entry + buyer_roster_daily_state: rolling 24-slot roster + daily inference state (migration 0039)
export * from './market_wear_mark';            // D1b C4 — lot_handling_vector (REUSE 04a preview hook) + district_wear_mark_demographics: wear-mark state per lot + per district (migration 0040)
export * from './market_district_capacity_state'; // D1b C5 — district_capacity_state: per-district hidden carrying-capacity state (migration 0041)
export * from './precursor_market_state';          // D1c B2 — precursor_market_state (global per-type, migration 0042) + precursor_supplier_pressure (per player×supplier, migration 0043)
export * from './reputation_state';               // D2 R1 — 6 reputation entities: boss_mirror_violation_ring (0045) + boss_mirror_declaration_ledger (0046) + restraint_dispute_ring (0047) + hidden_curriculum_norms_vector (0048) + forbidden_triad_pair_state (0049) + lek_memory_cell_state (0050 — DD-LEK-LOC sibling)
export * from './insurance';                       // Insurance C1 — 4 insurance entities: underwriter_walk_record (0059) + insurance_contract (0060) + insurance_claim (0061) + almanac_entry (0062) + 6 pgEnums (coverageType/walkStatus/contractStatus/claimStatus/almanacStatus/claimBasis)
export * from './forensic';                        // Forensic C1 — 2 forensic entities: ledger_entry_ring (0071) + forensic_soft_flag_ring (0071)
export * from './conflict_rival';                  // 04b-A C1 — 1 rival entity: rival_state (0081) + 4 pgEnums (rivalKey/rivalRegime/intelMode/erosionRegisterId)
export * from './conflict_combat';                 // 04b-B C1 — 2 combat tables (combat_operation, combat_event) + 2 enums (combatEventType, partitionState); migrations 0085-0086
export * from './conflict_escalation';             // 04b-B C1 — 6 escalation/deesc/dead-hand tables + flow_regime enum; migrations 0087-0089
export * from './conflict_diplomacy';              // 04b-C C1 — 7 diplomacy tables (diplomacy_pair_state, credibility_state, public_ledger_entry + 4 pact tables) + 6 enums; migrations 0094-0095
export * from './conflict_infowar';               // 04b-C C9 — 4 info-warfare tables (dead_reckoning_belief, dual_use_signal_state, surveillance_op, purge_trap_state); migration 0096
export * from './legal';                          // 04d-A C1 — 2 legal entities (lawyers, legal_cases) + 4 pgEnums (lawyerTier/chargeSeverity/caseStatus/defendantType); migrations 0097-0098
export * from './internal_affairs';               // 04d-B C1 — 3 IA entities: internal_affairs_targets (GLOBAL, 0099) + ia_investigations (0100) + ia_intel_purchases (0101) + 4 pgEnums (iaTargetType/iaInvestigationStatus/iaSuspicionBand/burnMethod)
export * from './region';                          // 04d-C C1b — 2 geo-region entities: region (PK region_id varchar(16), ~10 seeded [PROV-Y26Q2] + 'unknown') + region_country_map (country_code char(2) → region_id FK; 0102)
export * from './meta_market';                     // 04d-C C2 — 3 meta-market entities: meta_market_signals (PK composite region×substance×district×hour; bigint prices; 0103) + meta_market_contributions (contributor_hash ONLY — no raw player_id; HMAC-hashed; 0104) + meta_market_cohort_flags (anti-cheat; 0104)
export * from './effect_modifier';                 // 04e-A1 C2 — 2 effect-engine entities: political_event_active (GLOBAL city-wide lifecycle ledger, 0106) + effect_modifier (FK -> political_event_active CASCADE, the revert-guaranteed overlay row, 0106) + 3 pgEnums (effectScope/effectModifierOp/politicalEventCategory)
export * from './political_calendar_state';        // 04e-A2 C2 — political_calendar_state: singleton city-global calendar-tick watermark (last_evaluated_game_day) + scandal_noise_accumulator (C3 consumer), migration 0111
export * from './rival_elimination_ledger';         // 04e-A2 C3 — rival_elimination_ledger: per-player RivalEliminatedEvent history (E-POL-11 "2+ in 6mo"), migration 0112
export * from './political_district_signal_state';  // 04e-A2 C3 — political_district_signal_state: per-district E-POL-12 sustained-good-behavior window (consecutive_good_days), migration 0113
export * from './live_ops_event_active';            // 04e-B C2 — live_ops_event_active: the live-ops activation ledger (one row per activation, cohort_key + real-clock started_at/ends_at) + 2 pgEnums (liveOpsEventCategory/liveOpsActiveStatus); migration 0114. Same migration ALSO generalizes effect_modifier.ts (DD-B2 dual-FK, additive) — see that file's own header.
export * from './live_ops_aggression_ledger';       // 04e-B C6 — live_ops_aggression_ledger: per-player AssaultCascadeCompletedEvent history backing the AggressionScoreBucket composite (E-LO-06 "4+ violent ops/7d"), migration 0116 (was 0115 — DD-B4 took 0115 for live_ops_active_status.ENDED)
export * from './core_loops';                       // P3-A C1 — highest_leverage_cards: the HighestLeverageCard provider-registry's persisted row (session-open Loop 10 card, D11) + 1 pgEnum hl_card_status (active|committed|skipped|superseded); migration 0120 (renumbered from PROVISIONAL 0119 at P3-A+P3-B integration). gameplay_sessions/structural_decisions_audit/player_progression_state/exception_queue are REUSE-activated (D1/D7/D8/D10/D4), zero schema change to any of them this migration.
export * from './flag_discipline';                  // P3-B C1 — ch05 Loop 2 (Flag Discipline): routine_items (per-day generator candidates, D4) + flagged_items (append-only flag history, canon FlagHistoryEntry realized AS these rows, R9.3) + lieutenant_flag_state (NEW 1:1 token-state table, D2 sub-decision #1 RATIFIED — `lieutenant` table NEVER ALTERed) + 3 pgEnums (routineGenerator/routineItemStatus/flaggedItemResolution); migration 0123 (P3-B, landed in main before this integration). `gameplay_sessions.opened_game_day` (D11, same migration) is mirrored in `sessions_and_audit.ts`, not here.
export * from './recruitment';                      // 04f-B C1 — recruitment_candidates + recruitment_quests (Lieutenant Recruitment Quests, G11) + 2 pgEnums (hireQuality/recruitmentQuestOutcome); migration 0124 (renumbered from EARMARKED 0120 at the P3-A+P3-B integration — decisions.md §11). loyaltySeedBucketPg + the 2 new `lieutenant` columns live in ./lieutenant.ts (circular-import avoidance, see that file's own header note).
export * from './supply_chain_loops';               // P3-C C1 — ch05 Loops 3-5 (Backpressure Trace / Sinuosity Debt / Mycelial Ledger): supply_chain_legs (per-LEG debt ledger, D2 — leg = logical edge (player,origin,dest), UNIQUE DB-enforced I1) + supply_node_pressure (per-NODE backpressure ledger, D7 — 1-1 table, soft-ref arrow, CHECK both bounds I5) + 1 pgEnum mycelialMaintenanceMode (quick_patch/structural_reinforce/reroute_bypass); migration 0125 (renumbered from PROVISIONAL 0124 at this integration — 04f-B merged first and kept 0124 for `recruitment_quests`). The 3 additive `route` columns (patch_count/last_rebuilt_at_tick/rebuild_completes_at_tick, same migration) are mirrored in `operational_chain.ts`, not here.
export * from './cue_annealing';                    // P3-D C1 — ch05 Loops 6-7 (Cue Stack Integrity / Annealing Window): named_sequences (Loop 6 saved-template snapshot, D7 — UNIQUE (player_id,name), cap 5 DB-atomic at insert not a CHECK) + annealing_state (Loop 7 per-(player,building) settling ledger, D8 ★#1(a) coexist-disjoint with Phase-11 lieutenant.settling_until_tick — CHECK both bounds throughput_multiplier (0,1]); ZERO pgEnum NEW (D1); migration 0127 (provisional — journal head on this base was 126). The 4 additive `cue_stacks` bookkeeping columns + partial UNIQUE index I1 (same migration) are mirrored in `queues_exceptions_cuestack.ts`, not here.
export * from './demolition_compression';           // P3-E C1 — ch05 Loops 8-9 (Demolition Mandate / Compression Week): friction_budget_state (1-1 per-player friction cache, §4.3) + replacement_option (up to 2 ranked candidates per decommissioned node, §7/★#5, UNIQUE (player_id,source_building_id,rank)) — migration 0132; compression_events (per-player cycle ledger, invariant I1 partial-UNIQUE (player_id) WHERE state IN ('open','active')) + compression_problem_entry (board triage rows, snapshot-at-fire D11, UNIQUE (compression_event_id,problem_key)) — migration 0133. ZERO pgEnum NEW (D1). The additive `buildings.acquired_at_tick` column (mig 0132, resolution R11/#19) is mirrored in `city_state.ts`, not here.
export * from './delegation_ratchet';                // P3-F C1 — ch06 MÈRE (Delegation Ratchet — Graduated Retirement / Promotion Lock / Recall Debt): graduation_events (append-only audit spine, BOTH directions GRADUATION|RECALL, D13, referenced by ch09/canon since Task 4 but never defined until now) + promotion_locks (ONE ROW PER RECALL — canon INACTIVE = no row, D10, index (unmanaged_window_state,window_end_tick) for the C8 HOURLY tick) + player_proficiency (PK composite (player_id,category_id) — the mastery_score shape, D8 frozen-then-realized, D9 last_accrued_session_id idempotency guard) — migration 0135. ZERO pgEnum NEW (D1-lot-wide convention). `mastery_score`/`player_progression_state` (ch09 mig 0002) are ACTIVATED, not touched — zero column/CHECK change, see `player_progression_state.ts`.
export * from './budgets_horizon';                    // P3-G C1 — ch06 successor lot (Budgets & Horizon): capability_adoptions (at most ONE adoption per capability per player, permanent v1, PK composite (player_id,capability_id)) + capability_debts (Isostatic Debt ledger, SAME PK shape, structural_debt numeric(8,2) CHECK >=0, decay_path varchar+CHECK, partial index (player_id) WHERE structural_debt>0 for the C8 HOURLY/8 tick) — migration 0137. ZERO pgEnum NEW here (D1-lot-wide convention). `possibility_horizon_cards` (ch09 Task 10) is EXTENDED, not touched by THIS file — enum member 'dismissed' + predicate_regressed/dismissed_at/surfaced_predicate_snapshot columns + the R10 unique-pair index (subsumes the plain player_capability_idx) are mirrored in `progression_structural.ts`, same migration.
export * from './vertical_horizon';                   // P3-H C1 — ch06 8th sub-lot (Vertical Horizon): execution_plans + execution_cycle_slots (Decision Horizon Lock, D2 — multi-cycle wrapper over a LIVE standing order) + script_stability_counters (per-(player,lieutenant) ratchet, D5) + player_metric_benchmarks (Benchmark Drift baseline ledger, D10, ★H-3 2-LIVE) + player_reanchor_quotas (weekly re-anchor quota, D11/D12) + 7 pgEnums (execution_plan_status/deviation_mode/deviation_severity/cycle_slot_status/constraint_condition_type/metric_kind/snapshot_source — R6 pins pressure_tier to smallint+CHECK, NOT an 8th enum, see the migration's own header) — migration 0141. The Pressure Inverse columns (pressure_tier/graduation_count_since_last_pressure_unlock/tier4_observation_until_tick, design §3 divergence #1) are mirrored in `player_progression_state.ts`, same migration.
export * from './city_epoch';                         // W1.1-d C1.1 — city_epoch: the SINGLETON city-global "current game-minute" row (design §C1.1) — a NEW player's city_sim_clock.game_minute is seeded FROM this (C1.3), not from 0, so signups at different real-world instants stay IN PHASE. C2/C3 (NOT this chunk) own advancing it. migration 0144.
export * from './tutorial_state';                     // W1.1-b C1 — tutorial_state: the tutorial overlay SYSTEM's own persistence (08c-owned in DOCUMENT since 2026-05, first BUILT here — design §0.2, 0 hits on 8 canon symbols repo-wide before this migration). PK (player_id, tutorial_id) — "shown at most once" structural (D8-2). player_progression_state.tutorials_opt_out (SAME migration, design D4) is declared in player_progression_state.ts, not here. migration 0146.
export * from './iap_catalogue';                       // W1.3-C1 — iap_sku_override: the ONLY persisted half of the IAP catalogue (A1 option (C)) — the 9 SKU definitions stay code-owned (iap-sku-catalogue.ts), this table carries the BO enabled/disabled toggle only (PK sku_id, no FK — the definition set is closed in code). migration 0147.
export * from './iap_ledger';                           // W1.3-C2 — marks_ledger: the append-only invariant ledger backing economy_states.marks (design §3-C2 — "no marks mutation without a same-tx ledger row"). Index player_id (1-N). migration 0148 (incl. a backfill for pre-existing W1.1-a welcome-grant rows).
export * from './iap_entitlement';                      // W1.3-C3 — iap_entitlement: which COSMETIC/SAVE_SLOT SKUs a player owns (Marks-purchased). PK composite (player_id, sku_id) — re-acquisition impossible BY CONSTRAINT (design §3-C3). migration 0149.
export * from './two_person_approval';                  // W1.2-a — two_person_approval : le workflow d'approbation à deux opérateurs de ch17 (`authorization_rbac.md:134-159`), qui N'EXISTAIT SOUS AUCUNE FORME avant ce lot (mesuré : 183 pgTable dans services/**, zéro dont le nom porte approv/two/person, contrôle positif à l'appui) alors que 3 colonnes de production le référençaient déjà en soft-ref (anti_cheat.ts:69,98 · tunable_overrides.ts:9). R-RBAC-3 (initiator ≠ approver) est portée par un CHECK EN BASE, pas par le service : une garde de service ne protège que les appelants qui passent par le service. Le CHECK d'état ferme le monde dégénéré que le premier laisse passer — APPROVED par personne. L'index d'unicité est PARTIEL (les états terminaux coexistent en historique) et porte NULLS NOT DISTINCT, sans quoi il serait vert précisément dans le cas qu'il existe pour couvrir. migration 0152, les 4 attaques et 3 contrôles rejoués contre une base PG 16 réelle.
